### ISSUE TITLE
question about the packet decoder

### ISSUE THREAD

**Issue by recklessMo** [topfreegames/pitaya#123]
https://github.com/topfreegames/pitaya/blob/287b60e35ecae869b29d87df0b782969b4bf0c09/service/handler.go#L193

If a client sends  a packet of 1500 bytes,  but the underlying connection only read 1000 bytes for the first read attempt and for the second attempt it read the remaining 500 bytes, which I think is possible.

The referring code will cause decode error because it doesnot have enough bytes and it will discard the first 1000 bytes.  how to resolve this case ？

**Comment by felipejfc** [comment]
Hi @recklessMo, you're partially right. Fragmentation can occur in the network level, e.g.

You send a chunk of 2000 bytes but the receiver's network has an MTU of 1500 bytes, what will happen in that case is that the chunk will be fragmented in the network layer but then reassembled at the receiving part. What's important to keep in mind is that this will happen at the network layer, so that will be transparent at the application level.

Given that, it should never happen that we read an incomplete chunk of data in this function. However, keep in mind that the current code only supports receiving packets with a maximum size of 2kb from the clients. We shall make that configurable soon.

Best!

**Comment by recklessMo** [comment]
> Hi @recklessMo, you're partially right. Fragmentation can occur in the network level, e.g.
> 
> You send a chunk of 2000 bytes but the receiver's network has an MTU of 1500 bytes, what will happen in that case is that the chunk will be fragmented in the network layer but then reassembled at the receiving part. What's important to keep in mind is that this will happen at the network layer, so that will be transparent at the application level.
> 
> Given that, it should never happen that we read an incomplete chunk of data in this function. However, keep in mind that the current code only supports receiving packets with a maximum size of 2kb from the clients. We shall make that configurable soon.
> 
> Best!
@felipejfc   Thanks for the reply. And forgive me for my poor english. 

But I donnot think fragmentation is thansparent to the application level.   According to your example, if the client send a chunk of 2000 bytes, which is under 2kb of course,  the server first receive 1500 bytes, then it will execute the decode logic and compose a packet with only 1500 bytes data and proceed with the `processpacket` function, which is wrong in this case. In the referring function, you use the `conn.read` function, so possibly it will return data with any length under that slice capacity,  this will cause the decode logic not function right.  

To prove that,  it you run the chat program under the example dir,  if one client send a packet larger than 1024 bytes and small than 2kb.  The program will work as expected, because the underlying conn has a read buffer of 1024bytes.

**Comment by felipejfc** [comment]
no problem @recklessMo 

You can find information on IP Fragmentation at the IP RFC [here](https://tools.ietf.org/html/rfc791) also, Wikipedia has a good summary [here](https://en.wikipedia.org/wiki/IP_fragmentation)

> If a receiving host receives a fragmented IP packet, **it has to reassemble the packet and pass it to the higher protocol layer**. Reassembly is intended to happen in the receiving host but in practice it may be done by an intermediate router, for example, network address translation (NAT) may need to reassemble fragments in order to translate data streams.[3]

https://github.com/topfreegames/pitaya/blob/287b60e35ecae869b29d87df0b782969b4bf0c09/service/handler.go#L182-L188

There we set our buffer size as 2kb, so, as long as your client send messages that are less than 2kb, you should be fine. If you want to test it out, the right way is sending a message > MTU and < 2kb, 1700 bytes for example (given that MTU=1500). This should work fine even though it's going to get fragmented at the network layer.

**Comment by recklessMo** [comment]
@felipejfc 

Thanks for the reply.

I don't think I hava made my points of view clear. Let me explain in detail.  I think there are two cases will cause your decode logic not function right,  event if client send packet < 2kb.

1.  If the client send 5 packets in a sequence and the length of each packet is 500 bytes,  which in total is 2500 bytes. In such case, if the server has enough bytes buffer, the server may receive 2500 bytes in a SINGLE read,  but we now ONLY have 2048 bytes，so the FIFTH packet will be incomplete and thus the decode logic will fail.  I also wrote a test program to prove this.  My point is that fragmentation may be transparent between network layer and transport layer, but it is not between transport layer and application layer. 

2.  the decode login use `conn.read` while the conn is a object implements `net.conn`  interface,  for example in the chat program under the example dir,  the `conn` is a websocket, and its buffer size has been set to 1024 bytes, so even if the web client send something between 1024 bytes and 2048 bytes, the server will not decode it right. You can run the program and send a message with 1500 bytes and the server will fail.  My point is that the decode logic is not strong enough,  it is strongly coupled with the underlying connnection implementation.

Best!

**Comment by felipejfc** [comment]
Hi @recklessMo 

1. I think that this should only happen if you are joining the packets together in the application layer, can I see your proof application? Anyways, if I got the problem right, this should be solved by #122 right?

2. Thanks for bringing this into attention! I think that once we merge #122, setting the buffer to 4096 might solve this problem. Still, I agree with you that the decode logic should be less coupled with the underlying connection implementation, do you have any suggestion?

**Comment by felipejfc** [comment]
@recklessMo 

Now I get what you were trying to say, it's true that we can receive half-messages because TCP is a stream-oriented protocol, not message-oriented.
We could change the code at pitaya/service/handler.go for inserting a logic there that would parse whole messages and only then send them for processing, but even that wouldn't be very elegant because this layer receives messages from the acceptor itself that could do this already by itself in some cases (websocket, for example, is message-based).
I'll rethink the implementation between acceptor <-> handler .

I believe that PR #124 the way it is should solve the problem for WebSocket acceptor since it is message-based and we are not limiting the buffer size in the wrong way anymore. But not for TCP, since it's stream-based.

Best
