### ISSUE TITLE
Does this server support RUDP ? 

### ISSUE THREAD

**Issue by meiry** [topfreegames/pitaya#178]
Hello folks 
Reading your documents I see you are supporting only TCP and WS.
don't you need for your games RUDP implementation ? 
Do i miss something? 
Thanks

**Comment by felipejfc** [comment]
we didn't need rudp so far for pitaya because for gameplay servers we're using other frameworks. however, it should be really simple to add support to kcp for example, it's only a matter of implementing the acceptor interface using kcp as backend

**Comment by meiry** [comment]
@felipejfc 
Thanks for your answer.  
So if i understand you right, you are not using this server for mobile multiplayer games? (as this is the main traction of this project no? ) 
What do you use as your multiplayer server if i may ask?

**Comment by leohahn** [comment]
We use this framework for building mobile servers that are not as performance-sensitive, like metagames. We did not had the necessity to add RUDP support because of that.

However, like Felipe said, nothing stops the framework to be used for gameplay logic using  RUDP. We would only need to add support on Pitaya itself and on the client (libpitaya). 

One option here would be, for example: https://github.com/ValveSoftware/GameNetworkingSockets
