### ISSUE TITLE
Does rpc support asynchronous requests?

### ISSUE THREAD

**Issue by suntianji123** [topfreegames/pitaya#181]

**Comment by chgz** [comment]
probably not.
i think you don’t need to use asynchronous requests to use go.

**Comment by felipejfc** [comment]
You should not need async requests. We've benchmarked pitaya with both NATS and GRPC framework and were able to get to dozens of thousands of requests per second in the same server instance. Since pitaya is made for horizontal scalability then you should be fine...
Keeping it "synchronous" also helps with code readability, one of the reasons we made pitaya was because the former framework we worked with was written in js and had the infamous "callback hell" problem.

If you really need async requests, please describe why in a new issue.
