### ISSUE TITLE
nano authors deserve credit

### ISSUE THREAD

**Issue by allyraza** [topfreegames/pitaya#2]
Hi I see you guys just copy pasted nano and started building on it without giving the original author any credit I think nano authors deserve at least that much.

**Comment by felipejfc** [comment]
and I think you should read the LICENSE file before saying that

**Comment by cscatolini** [comment]
Hi @allyraza, we reference nano authors in the LICENSE file and in the beginning of all files that came from that project. I've also updated the readme to give them credit. 

I'm closing this issue since I think that's enough for now. If you disagree feel free to reopen this and suggest how we could better give them credit.

**Comment by allyraza** [comment]
@felipejfc I saw the license file before I created the issue, if you guys add them in README they will be more reasonable. 

Also you don't have to be jerk when replying to tickets, learn something from your colleague/peer.

**Comment by felipejfc** [comment]
@allyraza the jerk is the one accusing people of copying things without giving credits when they did
