### ISSUE TITLE
Will there be a tcp sticking problem?

### ISSUE THREAD

**Issue by lx-world** [topfreegames/pitaya#206]
Will there be a tcp sticking problem?

**Comment by chgz** [comment]
nope

**Comment by lx-world** [comment]
https://github.com/topfreegames/pitaya/blob/master/conn/codec/pomelo_packet_decoder.go#L44

I think the buff should be connected to the global

**Comment by lx-world** [comment]
> nope

我认为这里https://github.com/topfreegames/pitaya/blob/master/conn/codec/pomelo_packet_decoder.go#L44， buff不应该每次都创建新的， 应该是每个连接 全局的，否则， tcp出现粘包的话，数据就会发生错误

**Comment by felipejfc** [comment]
we use a single PacketDecoder to decode from all the connections, then I would bet we would have problems reutilizing the same buffer, especially since there's also thread concurrency calling the Decode method.

What we can maybe do however is to use a thread pool to reduce allocations there, but this would be performance improvement only

**Comment by lx-world** [comment]
> we use a single PacketDecoder to decode from all the connections, then I would bet we would have problems reutilizing the same buffer, especially since there's also thread concurrency calling the Decode method.
> 
> What we can maybe do however is to use a thread pool to reduce allocations there, but this would be performance improvement only

I think something like this,

https://github.com/lonng/nano/blob/master/internal/codec/codec.go#L72

**Comment by felipejfc** [comment]
Nano's architecture allows them to do this, ours don't
