### ISSUE TITLE
MaxPacketSize excced error.

### ISSUE THREAD

**Issue by arden** [topfreegames/pitaya#98]
We used to transfer files when using pitaya, but there was an error that the size exceeded 64k. Can MaxPacketSize be modified to be configured through the configuration file?

**Comment by felipejfc** [comment]
hi @arden, can you send a project that we can use for reproducing the problem?

**Comment by arden** [comment]
in this file:  pitaya/conn/codec/constants.go
```
package codec

import "errors"

// Codec constants.
const (
	HeadLength    = 4
	MaxPacketSize = 64 * 1024
)

// ErrPacketSizeExcced is the error used for encode/decode.
var ErrPacketSizeExcced = errors.New("codec: packet size exceed")
```
This is because the packet size is too large, but MaxPacketSize is hard-coded, which is more flexible if you can configure this parameter in a configuration file.

**Comment by felipejfc** [comment]
The pomelo packet codec uses the following structure for a packet:
```
//
// -<type>-|--------<length>--------|-<data>-
// --------|------------------------|--------
// 1 byte packet type, 3 bytes packet data length(big end), and data segment
```
Because it uses only 3 bytes for data length, the maximum data size you could send with it would be 16777215 bytes (16mb), would this be enough for you? I don't see any problems increasing the max len to 16mb since it seems that we are waisting one byte now...
If you need more than 16mb I suggest you make a PR with a new packet encoder/decoder that would allow you more than 3 bytes for data len.

**Comment by arden** [comment]
Now, Sending a packet of more than 64kb will now report this error ( codec: packet size exceed ), not to mention 16M.

**Comment by felipejfc** [comment]
I meant that we could increase it to 16mb without any problems

**Comment by felipejfc** [comment]
I increased the max packet size to 16mb in tag v0.12.3, making this variable configurable would not make sense for pomelo codec because 16mb is the max value, if you need more than that I suggest that you create your own packet encoder/decoder in both this project and libpitaya (for the client)
